### ISSUE TITLE
s3 manager does not work with object store having self signed certificates

### ISSUE THREAD

**Issue by vamseekrishna25** [mastertinner/s3manager#14]
many object like Noobaa and others when hosted with self signed certificate require the s3 clients to connect with skip ssl verfiy
 as and example the amazon s3 client also gives a provision to skip ssl verfiy for s3 compatible object store hosted with self signed certificate 
 aws --endpoint xxxxx  --no-verify-ssl s3 mv s3:xxxx aws-bucket-data/pod.yaml
 
 hence need to enhance s3 manager with USE_Skip_SSL_Verification option in environment variable
 i have patched this issue by adding the above option
 https://github.com/mastertinner/s3manager/commit/4b00800bf9bc0556f7270b953698696d12b50555

**Comment by mastertinner** [comment]
Thanks, @vamseekrishna25. I implemented this with https://github.com/mastertinner/s3manager/commit/346ee86107aa309d916a94d901005105732246bb

I hope that also fixed it for you :)

**Comment by vamseekrishna25** [comment]
yes Thank You
