### ISSUE TITLE
No releases :)

### ISSUE THREAD

**Issue by nervo** [mastertinner/s3manager#15]
Hi, any chances to have some downloadable releases ? Using https://goreleaser.com/ for instance

**Comment by mastertinner** [comment]
Good idea. I added GoReleaser with https://github.com/mastertinner/s3manager/commit/285881eb80317044094660ec7f6948e43b10a752 but I think there's not much use for it without the `web/templates` being emedded into the binary using [embed](https://golang.org/pkg/embed/). I'll look into that in the upcoming days and then create the first release.

**Comment by mastertinner** [comment]
I just embedded the templates into the Go binary and created a first release: https://github.com/mastertinner/s3manager/releases/tag/v0.1.0 :tada: 

Thanks for the good idea, @nervo!
